Changes

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -58,6 +58,14 @@ Resources:
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/CloudWatchFullAccess
         - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
+      Policies:
+        - PolicyName: ec2DescribeTags 
+          PolicyDocument:
+            Version: 2012-10-17
+            Statement:
+              - Effect: Allow
+                Action: 'ec2:DescribeTags'
+                Resource: '*'
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
@@ -133,7 +141,7 @@ Resources:
                   Category: Source
                   Owner: ThirdParty
                   Provider: GitHub
-                  Version:  1
+                  Version:  "1"
               OutputArtifacts:
                 - Name: Source
               Configuration:
@@ -150,7 +158,7 @@ Resources:
                   Category: Build
                   Owner: AWS
                   Provider: CodeBuild
-                  Version: 1
+                  Version: "1"
               InputArtifacts:
                 - Name: Source
               OutputArtifacts:
@@ -167,7 +175,7 @@ Resources:
                   Category: Deploy
                   Owner: AWS
                   Provider: CodeDeploy 
-                  Version: 1
+                  Version: "1"
               Configuration:
                 ApplicationName: !Ref DeploymentApplication
                 DeploymentGroupName: !Ref StagingDeploymentGroup
@@ -195,15 +203,37 @@ Resources:
     Type: AWS::EC2::Instance
     CreationPolicy:
       ResourceSignal:
-        Timeout: PT15M
+        Timeout: PT45M
         Count: 1
+    Properties:
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+  
+  Instance2:
+    Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT45M
+        Count: 1
+    Properties:
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+  
+  InstanceLaunchTemplate:
+    Type: AWS::EC2::LaunchTemplate
     Metadata:
       AWS::CloudFormation::Init:
         config:
           packages:
             yum:
-              wget: []
-              unzip: []
               ruby: []
               jq: []
           files:
@@ -215,64 +245,80 @@ Resources:
               command: "./install auto"
               cwd: "/home/ec2-user"
     Properties:
-      ImageId: !Ref EC2AMI
-      InstanceType: !Ref EC2InstanceType
-      IamInstanceProfile: !Ref InstanceProfile
-      Monitoring: true
-      KeyName: justinthebastion
-      SecurityGroupIds:
-        - !GetAtt SecurityGroup.GroupId
-      UserData:
-        Fn::Base64: !Sub |
-          #!/bin/bash -xe
+      LaunchTemplateName: !Sub 'LaunchTemplate_${AWS::StackName}'
+      LaunchTemplateData:
+        ImageId: !Ref EC2AMI
+        InstanceType: !Ref EC2InstanceType
+        IamInstanceProfile:  
+          Arn: !GetAtt  InstanceProfile.Arn
+        Monitoring: 
+          Enabled: true
+        KeyName: justinthebastion
+        SecurityGroupIds:
+          - !GetAtt SecurityGroup.GroupId
+        UserData:
+          Fn::Base64: !Sub |
+            #!/bin/bash -xe
 
-          # send script output to /tmp so we can debug boot failures
-          exec > /tmp/userdata.log 2>&1
+            # send script output to /tmp so we can debug boot failures
+            exec > /tmp/userdata.log 2>&1
 
-          # Update all packages
-          yum -y update
+            # Update all packages
+            yum -y update
 
-          # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
-          yum install -y aws-cfn-bootstrap
+            # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
+            yum install -y aws-cfn-bootstrap
 
-          # Have  Cloudformation install any files and packages from the metadata
-          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-          
-          cat > /tmp/install_script.sh << EOF
-          # START
-          echo "Setting up NodeJS Environment"
-          curl curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
+            # Have  Cloudformation install any files and packages from the metadata
+            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+            
+            cat > /tmp/install_script.sh << EOF
+            # START
+            echo "Setting up NodeJS Environment"
+            curl curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
 
-          # Dot source the files to ensure that variables are available within the current shell
-          . /home/ec2-user/.nvm/nvm.sh
-          . /home/ec2-user/.bashrc
+            # Dot source the files to ensure that variables are available within the current shell
+            . /home/ec2-user/.nvm/nvm.sh
+            . /home/ec2-user/.bashrc
 
-          # Install NVM, NPM, Node.JS
-          nvm alias default v12.7.0
-          nvm install v12.7.0
-          nvm use v12.7.0
-
-
-          # Create log directory
-          mkdir -p /home/ec2-user/app/logs
-          EOF
-
-
-          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
-          sleep 1; su - ec2-user -c "/tmp/install_script.sh"
-
-          # Have Cloudformation install any files and packages from the metadata 
-          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-          # Signal to CloudFormation that the instance is ready
-          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+            # Install NVM, NPM, Node.JS
+            nvm alias default v12.7.0
+            nvm install v12.7.0
+            nvm use v12.7.0
 
 
-      Tags:
-        - Key: Name
-          Value: !Ref AWS::StackName
+            # Create log directory
+            mkdir -p /home/ec2-user/app/logs
+            EOF
+
+
+            chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+            sleep 1; su - ec2-user -c "/tmp/install_script.sh"
+
+            # Have Cloudformation install any files and packages from the metadata 
+            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource InstanceLaunchTemplate
+
+            # Query the EC2 metadata service for this intance's instance-id
+            export INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
+
+            # Query the EC2 describeTags method and pull out the CFN Logival ID for this instance
+            export LOGICAL_ID`aws --region ${AWS::Region} ec2 describe-tags \
+            --filters "Name=resource-id,Values=${!INSTANCE_ID}" \
+            "Name=key,Values=aws:cloudformations:logical-id" \
+            | jq -r ".Tags[0].Value"`
+            # Signal to CloudFormation that the instance is ready
+            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource ${!LOGICAL_ID}
+
+
 Outputs:
-  InstanceEndpoint:
-    Description: The DNS name for the created instance
+  InstanceEndpoint1:
+    Description: The DNS name for instance 1
     Value: !Sub "http://${Instance.PublicDnsName}:8080"
     Export:
-      Name: InstanceEndpoint
+      Name: InstanceEndpoint1
+
+  InstanceEndpoint2:
+    Description: The DNS name for instance 2
+    Value: !Sub "http://${Instance2.PublicDnsName}:8080"
+    Export:
+      Name: InstanceEndpoint2
